config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users
resource :session, only: [:new, :create, :destroy]
resources :bands
resources :albums
resources :tracks

# root to: redirect('/users')
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id      :integer          not null, primary key
#  band_id :integer          not null
#  title   :string           not null
#  year    :integer          not null
#  live    :boolean          default(FALSE), not null
#

class Album < ApplicationRecord
  validates :title, :year, :band_id, presence: true

  belongs_to :band,
    class_name: :Band,
    foreign_key: :band_id

  has_many :tracks,
    class_name: :Track,
    foreign_key: :album_id,
    dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id   :integer          not null, primary key
#  name :string           not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
    class_name: :Album,
    foreign_key: :band_id,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks,
    dependent: :destroy
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id       :integer          not null, primary key
#  ord      :integer          not null
#  album_id :integer          not null
#  lyrics   :text
#  bonus    :boolean          default(FALSE), not null
#  title    :string           not null
#

class Track < ApplicationRecord
  validates :album_id, :title, :ord, presence: true
  validates :bonus, inclusion: { in: [true, false] }
  validates :ord, uniqueness: {
    scope: :album_id, message: "Already track of this # on album"
  }

  belongs_to :album,
    class_name: :Album,
    foreign_key: :album_id

  has_one :band,
    through: :album,
    source: :band

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#
require 'bcrypt'
class User < ApplicationRecord

  validates :session_token, :email, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :generate_session_token

  attr_reader :password

  def reset_session_token!
    self.session_token = SecureRandom.base64(16)
    self.save!
  end

  def generate_session_token
    self.session_token ||= SecureRandom.base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    end
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login
  
  def show
    @album = Album.find_by_id(params[:id])
    render :show
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:success] = 'Album successfully created'
      redirect_to band_url(@album.band)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def destroy
    @album = Album.find_by_id(params[:id])
    band = @album.band if @album
    @album.destroy if @album
    redirect_to band_url(band)
  end

  private

  def album_params
    params.require(:album).permit(:title, :band_id, :year, :live)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def require_login
    unless logged_in?
      flash[:errors] = ['Must be logged in']
      redirect_to new_session_url
    end
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    flash[:success] = 'Logged In Successfully'
    redirect_to user_url(user)
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login
  
  def index
    render :index
  end

  def show
    @band = Band.find_by_id(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:success] = 'Band successfully created!'
      redirect_to bands_url
    else
      flash[:errors] = ['Cannot create band']
      @band_name = params[:band][:name]
      render :new
    end
  end

  def destroy
    @band = Band.find_by_id(params[:id])
    @band.destroy if @band
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if user
      login_user!(user)
    else
      flash[:errors] = ['Failed to log in']
      @email = params[:user][:email]
      render :new
    end
  end

  def destroy
    user = current_user
    if user
      user.reset_session_token!
      session[:session_token] = nil
      flash[:success] = 'Successfully logged out'
    else
      flash[:errors] = ['Logout failed due to unforeseen complications']
    end
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_login
  
  def show
    @track = Track.find_by_id(params[:id])
    render :show
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      flash[:success] = 'Track successfully created'
      redirect_to album_url(@track.album_id)
    else
      flash[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def destroy
    @track = Track.find_by_id(params[:id])
    album = @track.album if @track
    @track.destroy if @track
    redirect_to album_url(album)
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :title, :ord, :lyrics, :bonus)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
    else
      flash.now[:errors] = ['Failed to create user']
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user
      render :show
    else
      flash[:errors] = ['Something went wrong']
    end
  end


  private

    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/new.html.erb
<header>
  <title>Dirty Herbert's Music App</title>
</header>

<form action="<%= albums_url %>" method="post">
  <label>Album Title
    <input type="text" name="album[title]" value="<%=@album.title%>">
  </label>
  <label>Artist
    <select name='album[band_id]'>
        <% Band.all.each do |band| %>
            <option
                <%= "selected" if @album.band_id == band.id %>
                value="<%= band.id %>">
                <%= band.name %>
            </option>
        <% end %>
    </select>
  </label>
  <label>Year
    <input type="text" name="album[year]" value="<%= @album.year %>">
  </label>
  <label>Live?
    <input type="radio" name="album[live]" value='t'<%= "checked" if @album.live %>>
    <input type="radio" name="album[live]" value='f'<%= "checked" unless @album.live %>>
  </label>
  <button>Create Album</button>
</form>

app/views/albums/show.html.erb
<a href="<%= band_url(@album.band) %>">Back To Band</a>
<h1> <%= @album.title %> </h1>
<ul>
  <li>Artist: <%= @album.band.name %> </li>
  <li>Year: <%= @album.year %></li>
  <li>Recorded Live: <%= @album.live %></li>
</ul>
<h3>Tracks</h3>
<a href='<%= new_track_url %>'>Add a Track</a>
<ul>
  <% @album.tracks.order('ord').each do |track| %>
     <li><%= track.ord %>  <a href='<%= track_url(track) %>'><%= track.title %></a></li>
  <% end %>
</ul>

app/views/bands/_band.html.erb
<h1><%= band.name %></h1>
<form action='<%= band_url(band) %>' method="post">
  <input type='hidden' name='_method' value='delete'>
  <button>Delete Band</button>
</form>

app/views/bands/index.html.erb
<% Band.all.each do |band| %>
  <ul>
    <li><%= render 'band', band: band %></li>
    <li><a href='<%= band_url(band) %>'><p>Visit Band Page</p></a></li>
  </ul>
<% end %>

app/views/bands/new.html.erb
<form action='<%=bands_url%>' method="post">
  <input type="text" name="band[name]" value='<%= @band.name %>' >
  <button>Register Band</button>
</form>

app/views/bands/show.html.erb
<%= render 'band', band: @band %>
<h1>Albums</h1>
<a href='<%= new_album_url %>'><p>Add Album</p></a>
<% @band.albums.order('year').each do |album| %>
  <a href='<%= album_url(album) %>'><li><%= album.title %>  (<%= album.year %>)</li></a>
  <form action="<%= album_url(album) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <button>Delete Album</button>
  </form>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>
    <% if flash[:success] %>
      <p><%= flash[:success] %></p>
    <% end %>
    <% if logged_in? %>
      <p>Hello, <%= current_user.email %></p>
      <a href='<%= user_url(current_user) %>'><p>Your Profile</p></a>
      <form action='<%= session_url %>' method="post">
        <input type="hidden" name="_method" value="delete">
        <button>Log Out</button>
      </form>
    <% else %>
      <%= link_to 'Log In', new_session_url %>
      <%= link_to 'Sign Up', new_user_url %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tracks/new.html.erb
<form action="<%= tracks_url %>" method="post">
  <label>Title
  <input type="text" name="track[title]" value="<%= @track.title %>">
  </label>
  <label>Album
    <select name="track[album_id]">
      <% Album.all.each do |album| %>
        <option <%= "selected" if @track.album_id == album.id %>
         value="<%= album.id %>"><%= album.title %></option>
      <% end %>
    </select>
  </label>
  <label>Track Number
    <input type="text" name="track[ord]" value="<%= @track.ord %>">
  </label>
  <label>Bonus
    <input type="radio" name="track[bonus]" value="true" <%= "checked" if @track.bonus %>>
    <input type="radio" name="track[bonus]" value="false" <%= "checked" unless @track.bonus %>>
  </label>
  <label>Lyrics
    <textarea name="track[lyrics]" rows="8" cols="80" value = "<%= @track.lyrics %>"></textarea>
  </label>
  <button>Create Track</button>
</form>

app/views/tracks/show.html.erb
<a href="<%= album_url(@track.album) %>">Back To Album</a>
<a href="<%= band_url(@track.band) %>">Back To Band</a>
<h1><%= @track.title %></h1>
<ul>
  <li>Track Number: <%= @track.ord %></li>
  <li>Album: <%= @track.album.title %></li>
  <li>Band: <%= @track.band.name %></li>
  <li>Bonus: <%= @track.bonus %></li>
</ul>

app/views/users/_user.html.erb
<p><%= user.email %></p>

app/views/users/new.html.erb
<form action='<%= users_url %>' method="POST">
  <label>Email
    <input type="text" name='user[email]' value='<%= @user.email %>' >
  </label>
  <label>Password
    <input type="password" name='user[password]'>
  </label>
  <button>Sign Up</button>
</form>

app/views/users/show.html.erb
<p><%= render 'user', user: @user %></p>
<a href= '<%= new_band_url %>'><p>Create Band</p></a>
<a href= '<%= bands_url %>'><p>Browse Bands</p></a>